import { NextResponse } from 'next/server';
import { GoogleGenAI, Type } from '@google/genai';

export async function POST(request: Request) {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

    const { query } = await request.json();

    if (!query || typeof query !== 'string' || !query.trim()) {
      return NextResponse.json({ error: 'Query is required' }, { status: 400 });
    }


    const systemInstruction = `
  You are the "News Cookie Chef", an advanced AI news analyst and trend predictor in 2026.
  The user will provide a brief, raw keyword (e.g., "Investment", "Idol", "AI").
  Your job is to interpret the contemporary context surrounding that keyword and expand it into exactly 3 distinct AI prompt options (cookies).
  
  🔥 [LANGUAGE RULE]: 
  Detect the language used in the user's query. 
  If the query is written in Korean, the generated 'text' for all options MUST be in Korean.
  If the query is written in English or any other language, the generated 'text' MUST be in English.
  
  You must follow this exact structural and thematic mapping for the 3 options:
  1. Option 1 (SQUARE): [Timeline & Impact] Focus on a chronological timeline or historical/future progression of the topic.
  2. Option 2 (CIRCLE): [Latest Trends & Hot Issues] Focus on the most recent trends, burning issues, or active public debates happening RIGHT NOW.
  3. Option 3 (HEXAGON): [Data & Statistics] Focus on extracting quantifiable data points, market sizes, or statistical metrics.
  
  Respond only in the requested JSON structure. Keep the prompt texts highly captivating, professional, and trend-focused.
`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Transform this raw query into 3 cookie prompts: "${query}"`,
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.ARRAY,
          description: 'List of 3 refined cookie prompt options',
          items: {
            type: Type.OBJECT,
            properties: {
              id: { type: Type.INTEGER, description: '1, 2, or 3' },
              shape: { type: Type.STRING, description: 'SQUARE, CIRCLE, or HEXAGON' },
              text: { type: Type.STRING, description: 'The refined prompt text generated by LLM' }
            },
            required: ['id', 'shape', 'text'],
          },
        },
      },
    });

    const responseText = response.text;
    if (!responseText) {
      throw new Error('Empty response from Gemini');
    }

    const refinedOptions = JSON.parse(responseText);

    return NextResponse.json({ success: true, data: refinedOptions });
  } catch (error: any) {
    console.error('🔥 [Gemini Oven Error]:', error);
    return NextResponse.json(
        { success: false, error: error.message || 'Failed to bake cookie options' },
        { status: 500 }
    );
  }
}